import matplotlib.pyplot as plt
import numpy as np
x=np.array(["java","python","php","javascript","c#","c++"])
y=np.array([22.2,17.6,8.8,8,7.7,6.7])
figure,axis=plt.subplots(2,2, figsize=(8,5))
axis[0,0].bar(x,y,color="skyblue")
axis[0,0].set_title("popularity of languages")
axis[0,0].set_xlabel("languages")
axis[0,0].set_ylabel("popularity")
axis[0,1].barh(x,y,color="lightgreen")
axis[0,1].set_title("popularity of languages")
axis[0,1].set_xlabel("languages")
axis[0,1].set_ylabel("popularity")
z=np.array(["yellow","purple","orange","pink","cyan","red"])
axis[1,0].bar(x,y,color=z)
axis[1,0].set_title("popularity of languages")
axis[1,0].set_xlabel("languages")
axis[1,0].set_ylabel("popularity")
axis[1,1].pie(y,labels=x,autopct="%1.1f%%",startangle=140)
axis[1,1].set_title("popularity of languages (pie chart)")
plt.show()