import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([1,2,3,4,5])
print("array a")
print(x)
print("array b")
print(y)
print("a>b")
print(np.greater(x,y))
print("a>=b")
print(np.greater_equal(x,y))
print("a<b")
print(np.less_equal(x,y))
print("a<=b")
print(np.less_equal(x,y))