import numpy as np
x=np.array([[1,0],[0,1]])
print("array")
print(x)
print("sum of all elements:")
print(np.sum(x))
print("sum of each coloumn:")
print(np.sum(x,axis=0))
print("sum of each row:")
print(np.sum(x,axis=1))
